# Generated by Django 5.0 on 2024-03-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_borrowed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
