# Generated by Django 5.0 on 2024-03-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_is_returned_alter_book_is_borrowed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
    ]
